services:
  db:
    build:
      context: .
      dockerfile: db.dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: {{DB_USER}}
      POSTGRES_PASSWORD: {{DB_PASSWORD}}
      POSTGRES_DB: {{DB_NAME}}
    command: ["postgres", "-c", "fsync=off", "-c", "log_statement=all"]
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{DB_USER}} -d {{DB_NAME}}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
